env:
  browser: true
  es2021: true
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: off
  import/prefer-default-export: "off"
  import/extensions: 
    - error
    - ignorePackages
    - js: always
